import {getProjects,putProject,makeId,putSetting,deleteProject,renameProject,duplicateProject,toggleFavorite,markUsed} from './storage.js';
import {notesHTML} from './versions.js';
const I18N={
 es:{new:'Nuevo Proyecto',projects:'Mis Proyectos',settings:'Ajustes',pc:'PC Virtual',console:'Consola Virtual',ai:'IA Jumbo',studio:'Jumbo Studio',mobile:'iOS y Android Unificados',newDesc:'Crea juegos, apps y mundos.',projectsDesc:'Abre tus proyectos guardados.',settingsDesc:'Tema, idioma y versiones.',pcDesc:'Escritorio interno de Jumbo.',consoleDesc:'Zona tipo consola.',aiDesc:'Asistente del ecosistema.',studioDesc:'Cine, texturas y animacion.',mobileDesc:'Compatibilidad experimental.',create:'Crear proyecto',name:'Nombre del proyecto',desc:'Descripcion',back:'Volver',created:'Creado',used:'Ultimo uso',noData:'Sin datos',rename:'Renombrar',duplicate:'Duplicar',delete:'Eliminar',favorite:'Favorito',use:'Abrir 3D'},
 en:{new:'New Project',projects:'My Projects',settings:'Settings',pc:'Virtual PC',console:'Virtual Console',ai:'Jumbo AI',studio:'Jumbo Studio',mobile:'iOS and Android Unified',newDesc:'Create games, apps and worlds.',projectsDesc:'Open your saved projects.',settingsDesc:'Theme, language and versions.',pcDesc:'Internal Jumbo desktop.',consoleDesc:'Console-style testing zone.',aiDesc:'Ecosystem assistant.',studioDesc:'Cinema, textures and animation.',mobileDesc:'Experimental compatibility.',create:'Create project',name:'Project name',desc:'Description',back:'Back',created:'Created',used:'Last used',noData:'No data',rename:'Rename',duplicate:'Duplicate',delete:'Delete',favorite:'Favorite',use:'Open 3D'}
};
let lang='es';
export function setCurrentLang(l){lang=l||'es';}
export function t(k){return (I18N[lang]&&I18N[lang][k])||I18N.es[k]||k;}
export const appDefs=[
 {id:'new',icon:'➕',key:'new',desc:'newDesc'},
 {id:'projects',icon:'📁',key:'projects',desc:'projectsDesc'},
 {id:'settings',icon:'⚙️',key:'settings',desc:'settingsDesc'},
 {id:'pc',icon:'🖥️',key:'pc',desc:'pcDesc'},
 {id:'console',icon:'🎮',key:'console',desc:'consoleDesc'},
 {id:'ai',icon:'🤖',key:'ai',desc:'aiDesc'},
 {id:'studio',icon:'🎬',key:'studio',desc:'studioDesc'},
 {id:'mobile',icon:'📱',key:'mobile',desc:'mobileDesc'}
];
export function appName(id){const a=appDefs.find(x=>x.id===id)||appDefs[0];return t(a.key);}
export function appButton(app){return '<button class="tile" onclick="Jumbo.openPage(\''+app.id+'\')"><span class="ico">'+app.icon+'</span><b>'+t(app.key)+'</b><small>'+t(app.desc)+'</small></button>';}
export async function pageContent(id){if(id==='new')return newProjectHTML();if(id==='projects')return await projectsHTML();if(id==='settings')return settingsHTML();if(id==='pc')return '<span class="tag">Modulo</span><h2>'+t('pc')+'</h2><p>'+t('pcDesc')+'</p><div class="panel"><b>Alpha 0.4</b><p>Base lista para escritorio, ventanas y archivos.</p></div>';if(id==='console')return '<span class="tag">Modulo</span><h2>'+t('console')+'</h2><p>'+t('consoleDesc')+'</p>';if(id==='ai')return '<span class="tag">Modulo</span><h2>'+t('ai')+'</h2><p>'+t('aiDesc')+'</p>';if(id==='studio')return '<span class="tag">Modulo</span><h2>'+t('studio')+'</h2><p>'+t('studioDesc')+'</p>';return '<span class="tag">Experimental</span><h2>'+t('mobile')+'</h2><p>'+t('mobileDesc')+'</p>';}
function newProjectHTML(){return '<span class="tag">Alpha 0.4</span><h2>'+t('new')+'</h2><p>Al crear un proyecto se abre una escena 3D basica de Jumbo Engine.</p><div class="form"><input id="projectName" placeholder="'+t('name')+'"><textarea id="projectDesc" rows="3" placeholder="'+t('desc')+'"></textarea><select id="projectType"><option>3D</option><option>2D</option><option>VR</option><option>App</option></select><select id="projectDevice"><option>Movil</option><option>PC</option><option>Web</option><option>Consola</option></select><button class="primary" onclick="Jumbo.createProject()">'+t('create')+'</button></div>';}
async function projectsHTML(){const ps=await getProjects();let html='<span class="tag">Index Store</span><h2>'+t('projects')+'</h2><p>Funciones oficiales: renombrar, duplicar, eliminar, favoritos y ultima vez usado.</p>';if(!ps.length)return html+'<div class="panel"><p>No hay proyectos todavia.</p></div>';return html+ps.map(p=>'<div class="panel project-card '+(p.favorite?'favorite':'')+'"><b>'+(p.favorite?'⭐ ':'')+p.name+'</b><p>'+p.type+' · '+p.device+'<br>'+t('created')+': '+fmt(p.createdAt)+'<br>'+t('used')+': '+fmt(p.lastUsedAt)+'</p><div class="project-actions"><button class="mini" onclick="Jumbo.openProject3D(\''+p.id+'\')">'+t('use')+'</button><button class="mini" onclick="Jumbo.renameProject(\''+p.id+'\')">'+t('rename')+'</button><button class="mini" onclick="Jumbo.duplicateProject(\''+p.id+'\')">'+t('duplicate')+'</button><button class="mini" onclick="Jumbo.favoriteProject(\''+p.id+'\')">'+t('favorite')+'</button><button class="mini" onclick="Jumbo.deleteProject(\''+p.id+'\')">'+t('delete')+'</button></div></div>').join('');}
function settingsHTML(){return '<span class="tag">Sistema</span><h2>'+t('settings')+'</h2><div class="panel"><b>Language / Lenguaje</b><div class="form"><button class="mini" onclick="Jumbo.setLang(\'es\')">Español</button><button class="mini" onclick="Jumbo.setLang(\'en\')">English</button></div></div><div class="panel"><b>Color de fondo</b><div class="form"><button class="mini" onclick="Jumbo.setTheme(\'dark\')">Negro</button><button class="mini" onclick="Jumbo.setTheme(\'light\')">Blanco</button><button class="mini" onclick="Jumbo.setTheme(\'jumbo\')">Verde Jumbo</button></div></div><div class="panel"><b>Fondo del launcher</b><div class="form"><button class="mini" onclick="Jumbo.setBg(\'lines\')">Lineas Jumbo</button><button class="mini" onclick="Jumbo.setBg(\'glow\')">Brillo</button><button class="mini" onclick="Jumbo.setBg(\'clean\')">Limpio</button></div></div><div class="panel"><b>Color de botones</b><div class="form"><button class="mini" onclick="Jumbo.setButtons(\'green\')">Verde/Oro</button><button class="mini" onclick="Jumbo.setButtons(\'blue\')">Azul</button><button class="mini" onclick="Jumbo.setButtons(\'red\')">Rojo/Oro</button><button class="mini" onclick="Jumbo.setButtons(\'purple\')">Morado</button></div></div><div class="panel"><b>Dock</b><div class="form"><select id="dock1">'+opts()+'</select><select id="dock2">'+opts()+'</select><select id="dock3">'+opts()+'</select><button class="primary" onclick="Jumbo.saveDock()">Guardar Dock</button></div></div><div class="panel"><b>Documentacion oficial</b><button class="primary" onclick="Jumbo.showDocs()">Ver versiones</button></div>';}
function opts(){return appDefs.map(a=>'<option value="'+a.id+'">'+t(a.key)+'</option>').join('');}
function fmt(v){if(!v)return t('noData');try{return new Date(v).toLocaleString(lang==='en'?'en-US':'es-MX');}catch(e){return v;}}
export async function createProjectFromForm(){const p={id:makeId(),name:document.getElementById('projectName').value.trim()||'Proyecto sin nombre',desc:document.getElementById('projectDesc').value.trim(),type:document.getElementById('projectType').value,device:document.getElementById('projectDevice').value,createdAt:new Date().toISOString(),lastUsedAt:null,favorite:false};await putProject(p);return p;}
export async function setTheme(tn){document.body.classList.remove('theme-dark','theme-light','theme-jumbo');document.body.classList.add('theme-'+tn);await putSetting('theme',tn);}
export async function setBg(b){document.body.classList.remove('bg-lines','bg-glow','bg-clean');document.body.classList.add('bg-'+b);await putSetting('bg',b);}
export async function setButtons(c){document.body.classList.remove('btn-green','btn-blue','btn-red','btn-purple');document.body.classList.add('btn-'+c);await putSetting('buttons',c);}
export async function setLang(l){setCurrentLang(l);await putSetting('lang',l);}
export async function saveDock(ids){await putSetting('dock',ids);}
export {notesHTML,deleteProject,renameProject,duplicateProject,toggleFavorite,markUsed,putSetting};
